# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sl1m/programming/source/sdl_core

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sl1m/programming/source/sdl_core

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sl1m/programming/source/sdl_core/CMakeFiles /home/sl1m/programming/source/sdl_core//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sl1m/programming/source/sdl_core/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sdl_core

# Build rule for target.
sdl_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sdl_core
.PHONY : sdl_core

# fast build rule for target.
sdl_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_core.dir/build.make CMakeFiles/sdl_core.dir/build
.PHONY : sdl_core/fast

core.o: core.cpp.o
.PHONY : core.o

# target to build an object file
core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_core.dir/build.make CMakeFiles/sdl_core.dir/core.cpp.o
.PHONY : core.cpp.o

core.i: core.cpp.i
.PHONY : core.i

# target to preprocess a source file
core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_core.dir/build.make CMakeFiles/sdl_core.dir/core.cpp.i
.PHONY : core.cpp.i

core.s: core.cpp.s
.PHONY : core.s

# target to generate assembly for a file
core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_core.dir/build.make CMakeFiles/sdl_core.dir/core.cpp.s
.PHONY : core.cpp.s

entity_manager.o: entity_manager.cpp.o
.PHONY : entity_manager.o

# target to build an object file
entity_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_core.dir/build.make CMakeFiles/sdl_core.dir/entity_manager.cpp.o
.PHONY : entity_manager.cpp.o

entity_manager.i: entity_manager.cpp.i
.PHONY : entity_manager.i

# target to preprocess a source file
entity_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_core.dir/build.make CMakeFiles/sdl_core.dir/entity_manager.cpp.i
.PHONY : entity_manager.cpp.i

entity_manager.s: entity_manager.cpp.s
.PHONY : entity_manager.s

# target to generate assembly for a file
entity_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_core.dir/build.make CMakeFiles/sdl_core.dir/entity_manager.cpp.s
.PHONY : entity_manager.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_core.dir/build.make CMakeFiles/sdl_core.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_core.dir/build.make CMakeFiles/sdl_core.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_core.dir/build.make CMakeFiles/sdl_core.dir/main.cpp.s
.PHONY : main.cpp.s

sdl_w.o: sdl_w.cpp.o
.PHONY : sdl_w.o

# target to build an object file
sdl_w.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_core.dir/build.make CMakeFiles/sdl_core.dir/sdl_w.cpp.o
.PHONY : sdl_w.cpp.o

sdl_w.i: sdl_w.cpp.i
.PHONY : sdl_w.i

# target to preprocess a source file
sdl_w.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_core.dir/build.make CMakeFiles/sdl_core.dir/sdl_w.cpp.i
.PHONY : sdl_w.cpp.i

sdl_w.s: sdl_w.cpp.s
.PHONY : sdl_w.s

# target to generate assembly for a file
sdl_w.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_core.dir/build.make CMakeFiles/sdl_core.dir/sdl_w.cpp.s
.PHONY : sdl_w.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sdl_core"
	@echo "... core.o"
	@echo "... core.i"
	@echo "... core.s"
	@echo "... entity_manager.o"
	@echo "... entity_manager.i"
	@echo "... entity_manager.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... sdl_w.o"
	@echo "... sdl_w.i"
	@echo "... sdl_w.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

